service: basic-serverless-lambda

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-2
  
functions:
  generateRandomNumber:
    handler: src/handler.generateRandomNumber
    events:
    - http: 
        path: /hello
        method: POST      #GET
    timeout: 60 # seconds
    memorySize: 128 # mb
