name: deploy to lambda
on:
  push:
    branches:
    - master
jobs:
  deploy_lambda:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [18.x]
    steps:
    - name: checkout source code
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy
      env:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
