name: deploy to lambda
on:
  push:
    branches:
    - master
    paths:
    - /home/alok/.nvm/versions/node/v16.19.1/bin/node
jobs:
  deploy_lambda:
    name: deploy lambda from source
    runs-on: self-hosted         #runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [16.x]   #[18.x]
    steps:
    - name: checkout source code
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
